"""add password_last_changed to user

Revision ID: 79fbedb83689
Revises: f032d3b911b4
Create Date: 2025-12-10 19:48:41.035436

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79fbedb83689"
down_revision: str | Sequence[str] | None = "f032d3b911b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "password_last_changed",
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_last_changed")
    # ### end Alembic commands ###
